### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by seethalelias-aot** [AOT-Technologies/forms-flow-ai#106]
Bug Report: Getting error in console

Issue: Could not connect to API server while submitting form

- formsflow.ai Version: forms flow v4
- Browser: Google chrome
- Browser version:  Version 91.0.4472.101 (Official Build) (64-bit)

### Steps to Reproduce

1.http://localhost:3000/form
2.login as client
3.submit a form

### Observed Behaviour
Screenshots:
![1](https://user-images.githubusercontent.com/83584866/121658215-bab5b680-cabe-11eb-9ad6-c4d124d6dc7d.PNG)
![2](https://user-images.githubusercontent.com/83584866/121658237-c1442e00-cabe-11eb-976e-1eabac62d16c.PNG)

Response: {"status":400,"message":"Cast to ObjectId failed for value \"formsflow-client@example.com\" (type string) at path \"_id\" for model \"submission\""}

**Comment by abhilash-aot** [comment]
This is currently a known issue and expected behavior. Will update in changelog know issues list for now.
 
- This occurs because we are having the list of users in keycloak only and not in formio Db. The react-formio (https://www.npmjs.com/package/react-formio) component by default checks for the user to be available in formio db with the /current api on each submission regardless of using a external user authentication which would fail in the scenario. 
_**-  You can ignore this error as such for now, it wont have any effect as such in the workflow submission.**_ 

 _We will try to update a fix on this in coming releases. :)_
