### ISSUE TITLE
How to use `POST to URL` submit action

### ISSUE THREAD

**Issue by uzrnem** [AOT-Technologies/forms-flow-ai#1069]
![image](https://user-images.githubusercontent.com/20123106/207564007-79b4e6cf-e685-45d1-8188-f078ef1d2afe.png)

How can I use formId, submissionId, processId in URL and Request header, also how can I pass customize data in `Post to Url` action of form?

**Comment by Josephalexantony-aot** [comment]
![image](https://user-images.githubusercontent.com/83585487/208073780-40258ef3-284e-4f3f-83a8-bc8aecd698f7.png)

We can use the action of the button as "custom" and add our own api url to fetch the data . The data fethed from the custom url can then be used as per the requirement.

**Comment by Josephalexantony-aot** [comment]
The custom action of the button provides a code space to add custom actions were we can add our url and get data using fetch fuchtion.

**Comment by Josephalexantony-aot** [comment]
here is a simple example that explains how to fetch data from a url in cutom button action. 
![image](https://user-images.githubusercontent.com/83585487/208074604-ae424b2c-a620-48e9-ba6a-64e289d9b984.png)

**Comment by Josephalexantony-aot** [comment]
For getting the url data to pass on the submit button click, we can use a hidden componant. In the data field of the hidden component, we can use the "calculated value" area to add our custom logic and url to attach on submit. 
![image](https://user-images.githubusercontent.com/83585487/208075652-8efd190d-4abd-4e3b-965c-9ca249786fa6.png)
![image](https://user-images.githubusercontent.com/83585487/208075977-be7a14ff-f806-4368-8e85-1d1a437e77c3.png)

**Comment by uzrnem** [comment]
@Josephalexantony-aot I think there is confusion, I wanted to know how can I submit form to custom URL and with custom form data by using button (POST to URL)

**Comment by Josephalexantony-aot** [comment]
Okay sorry for the inconveniance @uzrnem.
In this case you can customise the submit button. 
We will get the entire form data in 'data' object. see the example. 
![image](https://user-images.githubusercontent.com/83585487/208348234-da2872be-7098-43aa-9e0d-589f2f804aa2.png)
![image](https://user-images.githubusercontent.com/83585487/208348421-d8330ee9-9ddd-405c-884a-be58bcc2bdba.png)
You can customise the submit button to send the data through a custom url. 
=>Edit the submit button,
=>Make the action "custom" instead of "submit".
=>You can use fetch method to send the data. 
![image](https://user-images.githubusercontent.com/83585487/208348903-64bdf001-0304-4f9c-b815-033e347d1be1.png)
Here is a sample custom code for the submit button:

let options = {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json;charset=utf-8'
  },
  body: JSON.stringify(data)
}

fetch('https://example.com/api/endpoint', options)
  .then(response => response.json())
  .then(data => {
    // Do something with the response data
  });

**Comment by uzrnem** [comment]
@Josephalexantony-aot how can I append/pass formId, processId with data?

**Comment by uzrnem** [comment]
@Josephalexantony-aot just for reminder, did you got anything on this?

**Comment by Josephalexantony-aot** [comment]
You can see the hidden field added in the form like Application Status in the form designer. 
![image](https://user-images.githubusercontent.com/83585487/209755825-ec2574d5-6608-437c-8b80-aa03ede3ca8d.png)
same as you can add the fields as hidden component and call a camunda listner to get the process id and other field data to attach.
