### ISSUE TITLE
Formsflow won't shut down on port 3000

### ISSUE THREAD

**Issue by thesonpb** [AOT-Technologies/forms-flow-ai#1505]
### Please provide information about your setup

- formsflow.ai Version: [window desktop](https://aot-technologies.github.io/forms-flow-installation-doc/Pages/PC/windows/onWindows.html)
- Browser: Google Chrome
- Browser version: 114.0.5735.199

### Steps to Reproduce

1. Install (run the install bat file in the scripts folder)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/55339338/52a06ff1-a1ef-49de-b05a-93d1338cbc94)
2. After all the formsflow.ai web application appear on localhost:3000, I run the uninstall bat file in the scripts folder
3. Stop and delete all the docker containers and images
4. When I try to access localhost:3000, the title is still formsflow.ai and the site is still loading

### Observed Behaviour
Event after i tried to taskkill the task running on port 3000, it still happened.
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/55339338/9459799e-df24-4e7b-8d98-71652a180434)

**Comment by alanraju-aot** [comment]
This is due to the browser cache which is not removed while using uninstall script. In this case port 3000 is only loading but not viewing the contents. You can just inspect and see the network and console, where they say they can't fetch the resourse and could not map the contents properly, that is since you have uninstalled the software.

![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/94040192/7bff7f30-4ebf-440f-ad85-dbe441fd8322)

**Comment by thesonpb** [comment]
> This is due to the browser cache which is not removed while using uninstall script. In this case port 3000 is only loading but not viewing the contents. You can just inspect and see the network and console, where they say they can't fetch the resourse and could not map the contents properly, that is since you have uninstalled the software.
> 
> ![image](https://user-images.githubusercontent.com/94040192/251354537-7bff7f30-4ebf-440f-ad85-dbe441fd8322.png)

Great! It seems the issue was indeed related to the browser cache. Clearing the cache or accessing localhost:3000 on a different browser resolved the problem. Thank you for your assistance!
