### ISSUE TITLE
Analytics not showing up in the web app

### ISSUE THREAD

**Issue by darsana-dinesh** [AOT-Technologies/forms-flow-ai#154]
After creating a dashboard in Redash (port 7000) and publishing it, are there other changes to be made to make the dashboard available in the web app (port 3000) when logged in as a designer? Right now the dashboards are listed but on click, it does not load on to the UI. 
![image](https://user-images.githubusercontent.com/33888539/135566348-e524baa0-7703-470c-9cfd-b8701a190584.png)

**Comment by kurianbenoy-aot** [comment]
@darsana-dinesh what is the redash version you are using? Did you use the same docker-compose configuration which we have [provided here](https://github.com/AOT-Technologies/forms-flow-ai/tree/master/forms-flow-analytics)?

Also to understand the issue more it would be great if you can share screenshots of network tab, to see if it's caused due to any CORS issues?

**Comment by darsana-dinesh** [comment]
@kurianbenoy-aot 
Thank you for the response. We got it working now. The issue was that we had not enabled the 'Allow public access' in the 
Share Dashboard options. After enabling that, we were able to see the dashboards in the web app. 
Please update this in the docs for analytics if possible.

**Comment by kurianbenoy-aot** [comment]
Thanks @darsana-dinesh. We didn't know it was added in the documentation. We will add it to documentation in the upcoming release.
