### ISSUE TITLE
The Camunda component can't be rebuilt when a database already exists in its directory

### ISSUE THREAD

**Issue by zmezei-proxifile** [AOT-Technologies/forms-flow-ai#157]
### Please provide information about your setup

- formsflow.ai Version: v4.0.2
- Browser: (irrelevant)
- Browser version: (irrelevant)

### Steps to Reproduce

1. Have forms-flow-bpm up and running with its postgres database.
2. Try to rebuild with the following command, suggested by the documentation:
```
docker-compose -f docker-compose-windows.yml up --build -d
```

### Observed Behaviour

The build doesn't happen with the following error message:
```
$ docker-compose -f docker-compose-linux.yml up --build -d
Building forms-flow-bpm
error checking context: 'can't stat '/home/ec2-user/forms-flow-ai/forms-flow-bpm/postgres/camunda''.
ERROR: Service 'forms-flow-bpm' failed to build : Build failed
```

### Expected Behaviour

The build should run properly.

### Additional info

We managed to rebuild the software with the following process:
```
docker-compose -f docker-compose-linux.yml stop
sudo mv postgres/ ../postgres-backup
docker-compose -f docker-compose-linux.yml build
sudo mv ../postgres-backup postgres
docker-compose -f docker-compose-linux.yml up -d
```
Renaming postgres to postgres-backup-2021-10-05 was not enough in this case, the build process still found the directory with this name, had to move out of the component's directory.

**Comment by shibin-aot** [comment]
_The build doesn't happen with the following error message:_
Can you provide some more details? Did you move the camunda directory before you run this command? What was the purpose you rebuilt the whole project?
_Renaming postgres to postgres-backup-2021-10-05 was not enough in this case, the build process still found the directory with this name, had to move out of the component's directory._
Yeah because the data will be on the docker image as well I hope, removing the external volume directory will not be enough.
