### ISSUE TITLE
Please update the installation documentation

### ISSUE THREAD

**Issue by PeeK1e** [AOT-Technologies/forms-flow-ai#1572]
### Please provide information about your setup

- formsflow.ai Version: 5.2.0
- Browser: any
- Browser version: any

### Steps to Reproduce

1. Follow Instructions to setup [Fomsflow in docker](https://github.com/AOT-Technologies/forms-flow-ai/tree/develop/deployment/docker)
2. Spend Hours debuging

### Observed Behaviour

Server responds with `unauthorized`.

### Expected Behaviour

Server shows login-screen when opening `http://<url>:3001`.

# CAUSED BY
`NO_INSTALL` Variable not being documented and being set to `1` by default without any explanation why.
Also There are several inconsistencies in the `forms-flow-forms` docs. 
E.g. :
* [`FORMIO_CLIENT_UI` appearing multiple times here](https://github.com/AOT-Technologies/forms-flow-ai/tree/develop/forms-flow-forms#installation)
* [`FORMIO_CLIENT_UI` Undocumented here](https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/deployment/docker/README.md#forms-flow-forms-setup)
* [`NO_INSTALL` Undocumented here](https://github.com/AOT-Technologies/forms-flow-ai/blob/develop/deployment/docker/README.md#forms-flow-forms-setup)

**Comment by shuhaib-aot** [comment]
_will update the docs._ 
``` NO_INSTALL ``` env variable used to enable UI for Formio client. the value should be ``` 1 or 0 ```. if it is **1** then it will not install any UI and else it will install client UI. and when we check the Formio URL , if the value equal to 1 then the URL will show unauthorized because it will act like a backend application which we can access those URLs through token. you can check ``` http://<url>:3001/checkpoint ``` this url will return Formio up or down.

**Comment by abhilash-aot** [comment]
Latest version v5.2.1 has the updated documentation . Ref: with https://github.com/AOT-Technologies/forms-flow-ai/tree/master
