### ISSUE TITLE
Submission can not be done from client - Unauthorized 

### ISSUE THREAD

**Issue by SumitMtx** [AOT-Technologies/forms-flow-ai#227]
Hi,
I configured the roles also correctly by hitting the roles api and pasted in .env file. Is there any issues with request token?
Can you please help me resolving this error.
And one more thing where will i get this value "FORMIO_JWT_SECRET". Currently i copied the token from browser from token api, may be it will expire.
![image](https://user-images.githubusercontent.com/90691983/155516963-cdc61c07-bd67-4db4-ad88-f0194ca92978.png)

**Comment by kurianbenoy-aot** [comment]
@SumitMtx you can get the value of `FORMIO_JWT_SECRET` from whatever value you have set in [forms-flow-forms setup](https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker#forms-flow-forms-setup). By default value is `--- change me now ---` and don't copy the token from browser as it's keycloak token, and for the forms we are using a formio token.

I feel the submission is happening because `FORMIO_JWT_SECRET` is not setup correctly.

**Comment by SumitMtx** [comment]
@kurianbenoy-aot After changing  FORMIO_JWT_SECRET to default value now api connection is failing while click on submit form. screenshot is attached below.
![image](https://user-images.githubusercontent.com/90691983/155650654-52110307-8070-4e36-825a-85527f085e97.png)

**Comment by SumitMtx** [comment]
@kurianbenoy-aot @georgephilip-aot 
After few minutes of docker restart this error gone and still same error is there as in original question.
**Unauthorized**

Now i have default value of FORMIO_JWT_SECRET in .env file.

**Comment by SumitMtx** [comment]
@kurianbenoy-aot  @abhilash-aot Can you please help me resolve this issue. It is working fine for three default forms. But getting Unauthorized error after creating a new form and try to submit that from client.

**Comment by abhilash-aot** [comment]
@SumitMtx Can you give bit more context on the problem of new forms not submitting ? Did you save the forms in from the Ui or added it from postman or form.io Url ? You may just need to edit the form and save  back in the fromsflow UI as designer . Also have a recheck of roles IDs to make sure.
